### PR TITLE
[SWARM-1075] Deprecate camel-other in favour of specific fractions

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by heiko-braun** [comment]
test this please

**Comment by heiko-braun** [comment]
Depends on https://github.com/wildfly-swarm/wildfly-swarm/pull/340

**Comment by heiko-braun** [comment]
Hold until https://github.com/wildfly-swarm/wildfly-swarm/pull/340 is merged

**Comment by kenfinnigan** [comment]
In the future I would prefer if branches are not added to the main repo to create a PR

**Pull request closed without merging**
