### PR TITLE
Example of Docker and Wildfly-Swarm

### PR DESCRIPTION
**Pull request by thomasandersen77**
It is a basic JAX-RS service running inside a Docker container.

### CODE REVIEW

**Comment by emag** [comment]
// not essential comment

The WF-Swarm app has unnecessary depedencies(javaee-api, lombok, slf4) since it's a simple JAX-RS application.

So it would be nice just copy of [jaxrs](https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/jaxrs) or [jaxrs-shrinkwrap](https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/jaxrs-shrinkwrap) example for easy to understand.

It should be focused on Dokcer.

**Comment by kenfinnigan** [comment]
Might make sense to just name the module `docker-jaxrs`?

Also, where you have `Swarm` as a name we should probably make it `WildFlySwarm` due to legal

**Comment by kenfinnigan** [comment]
@thomasandersen77 If easier, I can make some changes before merging, didn't want to step on toes though

**Comment by thomasandersen77** [comment]
If you have the time I would very much appreciate it. You'll probably do in a lot less time as well :)

**Comment by thomasandersen77** [comment]
@emag should I remove the dependencies you mention?

**Comment by kenfinnigan** [comment]
@thomasandersen77 It's fine, I can look at that shortly

**Comment by thomasandersen77** [comment]
Thank you :)

**Comment by emag** [comment]
@thomasandersen77 

> should I remove the dependencies you mention?

Yes, but it's not essential. It would be better the application is minimal and the example focuses on only one thing, Docker.

Anyway, I leave the matter to @kenfinnigan :)

**Comment by thomasandersen77** [comment]
@emag I agree! :)

**Comment by kenfinnigan** [comment]
merged

**Comment by thomasandersen77** [comment]
Thank you :)

**Pull request closed without merging**
