### PR TITLE
SWARM-1116: Health API has moved to another package

### PR DESCRIPTION
**Pull request by heiko-braun**
Align with changes in master

### CODE REVIEW

**Comment by heiko-braun** [comment]
Depends on https://github.com/wildfly-swarm/wildfly-swarm/pull/398

**Comment by heiko-braun** [comment]
Needs to be tested when core is merged. Locally examples passes

**Comment by heiko-braun** [comment]
retest this please

**Comment by kenfinnigan** [comment]
FYI, this still won't pass until the main CI build has completed and -deploy CI has done

**Comment by heiko-braun** [comment]
ok, thanks for the heads up

**Comment by heiko-braun** [comment]
i'll merge it tomorrow morning

**Comment by kenfinnigan** [comment]
retest this please

**Comment by kenfinnigan** [comment]
retest this please

**Pull request merged**
