### PR TITLE
Some improvements to the test executions

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by heiko-braun** [comment]
retest this please

**Comment by kenfinnigan** [comment]
What's the reason for some of the tests being changed to use uberJar all the time?

**Comment by heiko-braun** [comment]
@kenfinnigan To get more test coverage of the different execution paths. I ran into issues where the examples tests succeeded, but in fact the uberjars did not work at all. Spreading some `useUberJar`'s across the build should prevent this and bring these exceptions forward.

**Comment by kenfinnigan** [comment]
Is it possible to find out why the uber jar profile and `useUberJar` result in different output?

With such a change, does it mean those examples are no longer tested with `wildfly-swarm:run`?

**Comment by heiko-braun** [comment]
@kenfinnigan No, they are tested using the same approach: `wildfly-swarm:start, execute test, wildfly-swarm:stop`. The main difference is that with `useUberjar` the StartMojo switches from a system classpath sceanrio, to a regular uberjar (module classpath) scenario. Take a look here: https://github.com/wildfly-swarm/wildfly-swarm/blob/master/plugin/src/main/java/org/wildfly/swarm/plugin/maven/StartMojo.java#L90

This effectively creates a different code execution path. I've already discussed this with @bobmcwhirter and I think we should get away from the system cp in `wildfly-swarm:start` at all. It doesn't really buy you much, but creates another area of maintenance.

**Comment by bobmcwhirter** [comment]
The :start case (opposed to :run) is typically integration tests which
should be happening after you have an uberjar built is the reasoning.

**Comment by kenfinnigan** [comment]
As it's running a different code path than without `useUberJar` it does mean that those examples are no longer being tested on the alternative code path, which does introduce a possibility of things slipping through.

Now it could be worth dropping the system classpath use case of `wildfly-swarm:run` but that's a separate discussion.

It does concern me that from your observations `useUberJar` results in a different code path than the uberjar profile. It's worth investigating why that is the case from my perspective

**Comment by heiko-braun** [comment]
Well, `useUberJar` starts the uberjar (`java -jar *-swarm.jar`) and executes the tests. Without it, the executor assembles a classpath string and uses it with a main class to start the container `java -cp ... foo.Main`. 

With these changes to some of tests, the examples tests also verify the uberJar case. Previously I had issues, because the tests succeeded, but in fact the uberjar was broken (did not even start) and nobody noticed.

**Comment by kenfinnigan** [comment]
Right, but that's my point.

If the uberjar profile tests on examples result in something broken, shouldn't we be investigating why its broken as opposed to just adding `useUberJar` to the default profile tests?

**Comment by heiko-braun** [comment]
Ah, I now get your point. It did investigate that and fix it of course. The `useUberJar` _has not been added to work around a problem_.  It has been added to bring similar issues forward the next time the uberjars might be broken. Makes sense?

**Comment by kenfinnigan** [comment]
That makes sense.

I'm still wondering though about how it wasn't noticed with the uberjar profile. Was the jar being built badly and the test didn't fail? Or the test failed but Maven didn't register a failure?

Would be nice if we could rely on the uberjar profile tests to fail when there's something wrong. At the moment it sounds like that's not the case and makes me wonder whether there's any point to running them at all

**Comment by heiko-braun** [comment]
We didn't have a long standing problem with examples, but due to my refactoring as part of SWARM-491, I introduced new issues that the examples test suite didn't catch. Neither did the core testsuite, because it solely uses arquillian tests, which yet use another execution path and don't exercise the uberjar as well. 

Moving forward we should revisit the core testsuite and make sure it contains an appropriate mix of execution/build scenarios to cover the largest area possible.

**Pull request merged**
