### PR TITLE
Updated to the latest Vaadin 8 version

### PR DESCRIPTION
**Pull request by mstahv**

### CODE REVIEW

**Comment by heiko-braun** [comment]
test this please

**Comment by mstahv** [comment]
Was that comment for me or for some other reviewer? The integration test in the project runs fine and visually the app looks exactly the same as before. I contributed the original example couple of years ago.

**Comment by mstahv** [comment]
BTW. Which is the preferred packaging, jar or war? Should we change this example to build jar instead of war?

**Comment by kenfinnigan** [comment]
If there are dependencies that need to be bundled, WAR is still the preference

**Pull request merged**
