### PR TITLE
Move gradle tests to gradle 3.1

### PR DESCRIPTION
**Pull request by heiko-braun**
See if this solves the issue.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
retest this please

**Comment by heiko-braun** [comment]
so many ways to write gradle wrongly :)

**Comment by bobmcwhirter** [comment]
Retest this please

**Comment by bobmcwhirter** [comment]
Seems you found another one?

**Comment by kenfinnigan** [comment]
closing for now

**Pull request closed without merging**
