### PR TITLE
[SWARM-1848] Minor security/keycloak example improvements

### PR DESCRIPTION
**Pull request by sberyozkin**
New section on how to start Keycloak with the Swarm server
Docker tag has been updated
Migration file has been updated with the export from KeyCloak 3.4.0.Final

### CODE REVIEW

**Comment by kenfinnigan** [comment]
add to whitelist

**Comment by kenfinnigan** [comment]
Thanks @sberyozkin, this looks good.

One question I would have is whether the realm json could be shrunk significantly? For instance, an example in the book I'm writing uses https://github.com/kenfinnigan/ejm-samples/blob/master/chapter9/keycloak/service-realm.json with all ids, etc removed from the file. Makes it very small and easy to comprehend

**Comment by sberyozkin** [comment]
Thanks; I tried to shrink it, KeyCloak does allow the partial exports, so only the realm info (such as wildfly-swarm-keycloak-example) can be exported, but unfortunately, partial export does not include the users, so a demo will not work since the user 'user1' will not exist when a Keycloak instance is auto-initialized from this partially exported content. 
I did consider proposing removing this exported content altogether and instead referring to Getting Started and providing the simple guidance on how to create a  wildfly-swarm-keycloak-example relam and the user1, etc. But hesitated because the demo would take a bit longer to run. 

That said, we can still enhance README with something like "Alternatively, instead of using the migration file, start KeyCloak using one of the described mechanisms (Locally installed, docker or Swarm), and create the realm and the user as follows..." 

One other option is indeed to also ship a partial realm only export and also describe how to add the users manually, which would still require users access Admin Console.

I'd probably go for providing a short guidance on how to manually set up a Keycloak instance from the scratch, does it sound OK ?

**Comment by sberyozkin** [comment]
Sorry, I did the partial export from the admin console and it is doc-ed that no users can be exported, but let me try from the command line...

**Comment by sberyozkin** [comment]
Indeed, passing "-Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.realmName=wildfly-swarm-keycloak-example -Dkeycloak.migration.usersExportStrategy=REALM_FILE" did produce a realm-specific content plus users, still 55K though, but is better nonetheless.

**Comment by kenfinnigan** [comment]
With the generated export realm json, I'm pretty sure it can be slimmed down by removing IDs, and whole sections that Keycloak generates itself from scratch if not present. One example of that I think is the authentication flows section.

Unfortunately it's a case of experimenting with removing things from the file and seeing if it still imports and also works!

**Comment by sberyozkin** [comment]
Np, if it is acceptable then I can def give it a try

**Comment by kenfinnigan** [comment]
Sure, I want you to feel free to play around and explore, as you're still new to most of this

**Comment by sberyozkin** [comment]
The idea I could trim down the file manually did not occur to me :-), as I thought it would have to match precisely the exported content for the import to work. But indeed, after quite a few tries, it is now only 4.3 K so it is not too bad. Removing few more clients won't save much more, and if the users log in into the admin console after the test has run they won't recognize it as most of the exported content has gone :-)

**Pull request merged**
