### PR TITLE
zipkin-jaxrs fraction example

### PR DESCRIPTION
**Pull request by pavolloffay**
https://issues.jboss.org/browse/SWARM-920

Example application with zipkin-jaxrs fraction reporting spans to zipkin server.

### CODE REVIEW

**Comment by pavolloffay** [comment]
@heiko-braun could you please review? I have updated main with your instructions [1], however, It still does not report any data to the server. It still uses `com.github.kristofa.brave.LoggingSpanCollector`.

[1]: https://gist.github.com/heiko-braun/ae45f6bbcf18d0934d176c18630c844e

**Comment by pavolloffay** [comment]
I have removed previous comment. I think the fraction has to be added to the container before deployment. Now it reports data to the sever :+1: .

**Comment by kenfinnigan** [comment]
could this be moved into the /jaxrs directory and we could just name it zipkin?

**Comment by pavolloffay** [comment]
PR updated. `zipkin-jaxrs` has been moved to `jaxrs/zipkin`.

**Pull request merged**
