### PR TITLE
fix messaging example

### PR DESCRIPTION
**Pull request by jmesnil**
* using the java:jboss/DefaultJMSConnectionFactory JNDI entry looks required to deploy properly the WAR
* use JMS 2.0 API and lambda to remove boilerplate code irrelevant to
  the example

### CODE REVIEW

**Comment by jmesnil** [comment]
Feel free to ignore this PR.

I'm playing with swarm and was not able to run the messaging example without changing the inVMConnectorName.

**Comment by bobmcwhirter** [comment]
I don't quite follow.  We do setup the DefaultJMSConnectionFactory (in the ee subsystem) now on HEAD in Git, to support @Injecting the messaging context.  Are there further changes required?

I do like lambda and removal of boilerplate.

**Comment by jmesnil** [comment]
This messaging example has no dependency on `wildfly-swarm-ee` so the DefaultJMSConnectionFactory is not setup. Adding a dep to `wildfly-swarm-ee` was not enough to fix it and I also had to add a dep to wildfly-swarm-jca (this one should likely be a dep of `wildly-swarm-messaging`).
With these 2 new deps, the code works again without changing the invm connector name.

I'm still figuring out how Swarm and WildFly interacts though, I may have missed something obvious...

**Comment by bobmcwhirter** [comment]
Ah, mayhap we should add a dependency between wildfly-swarm-messaging and wildfly-swarm-ee, unless that drags in entirely too much transitively.

**Comment by jmesnil** [comment]
`wildfly-swarm-ee` must depend on `wildly-swarm-messaging` (it's mandatory for EE to have a default JMS connection factory) but the reverse is not correct. 
I'll figure out why you need to have ee when you want to deploy a JAX-RS app as this is the part failing in the example.

**Comment by jmesnil** [comment]
Actually, I only need to add `wildfly-swarm-jca` dependency to run the example.
JCA is required because of [this resource](https://github.com/wildfly-swarm/wildfly-swarm/blob/master/messaging/runtime/src/main/java/org/wildfly/swarm/messaging/runtime/MessagingConfiguration.java#L133). Without JCA, there is no default pooled connection factory and the archive is not deployed.
I tried adding wildfly-swarm-jca-runtime dependency to messaging but that did not work. I'm not sure which module should have a JCA dependency (and whether it on wildfly or swarm...)

**Pull request closed without merging**
